import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { detectInstallBrowser, type InstallBrowser } from "@/lib/pwaInstall";
import { ArrowLeft, Chrome, CirclePlus, HelpCircle, Home, Menu, Share, ShieldCheck, Smartphone } from "lucide-react";
import { useLocation } from "wouter";

type Guide = { key: InstallBrowser; title: string; description: string; steps: Array<{ icon: typeof CirclePlus; title: string; text: string }>; source: string; sourceLabel: string };

const guides: Guide[] = [
  { key: "samsung", title: "Samsung Internet", description: "Crie um atalho seguro e evite o fluxo bloqueado pelo Play Protect.", steps: [{ icon: CirclePlus, title: "Procure o +", text: "Toque no ícone + junto à barra de endereço." }, { icon: Home, title: "Ecrã inicial", text: "Escolha Ecrã inicial para criar o atalho." }, { icon: Menu, title: "Alternativa", text: "Sem o +, abra o menu e escolha Adicionar ao ecrã inicial." }], source: "https://samsunginternet.github.io/docs/homescreen", sourceLabel: "Instruções Samsung Internet" },
  { key: "chrome_android", title: "Chrome no Android", description: "Use o botão de instalação ou o menu do Chrome.", steps: [{ icon: Chrome, title: "Abra no Chrome", text: "Aceda a tototalho.me no Google Chrome." }, { icon: Menu, title: "Abra o menu", text: "Toque nos três pontos no canto do navegador." }, { icon: Home, title: "Adicionar", text: "Escolha Instalar app ou Adicionar ao ecrã inicial." }], source: "https://developer.chrome.com/blog/how_chrome_helps_users_install_the_apps_they_value", sourceLabel: "Guia Chrome" },
  { key: "ios", title: "Safari no iPhone", description: "Adicione a Liga Toto Talho ao ecrã principal como app web.", steps: [{ icon: Share, title: "Partilhar", text: "No Safari, toque no botão Partilhar." }, { icon: Home, title: "Adicionar", text: "Escolha Adicionar ao ecrã principal." }, { icon: Smartphone, title: "Confirmar", text: "Mantenha Abrir como app web ativo e toque em Adicionar." }], source: "https://support.apple.com/guide/iphone/open-as-web-app-iphea86e5236/ios", sourceLabel: "Guia Apple" },
];

function GuideCard({ guide, detected }: { guide: Guide; detected: InstallBrowser }) {
  return <Card className={detected === guide.key ? "border-blue-400 ring-2 ring-blue-100" : "border-slate-200/60"}>
    <CardHeader><CardTitle className="flex items-center gap-2 text-slate-900"><Smartphone className="h-5 w-5 text-blue-600" />{guide.title}{detected === guide.key && <span className="rounded-full bg-blue-100 px-2 py-0.5 text-xs font-semibold text-blue-800">O seu navegador</span>}</CardTitle><CardDescription>{guide.description}</CardDescription></CardHeader>
    <CardContent><div className="space-y-3">{guide.steps.map((step, index) => { const Icon = step.icon; return <div key={step.title} className="flex gap-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-100 text-sm font-bold text-blue-700">{index + 1}</div><div><div className="flex items-center gap-2 font-semibold text-slate-900"><Icon className="h-4 w-4 text-blue-600" />{step.title}</div><p className="mt-1 text-sm text-slate-600">{step.text}</p></div></div>; })}</div><a className="mt-5 inline-flex text-sm font-semibold text-blue-700 underline underline-offset-4" href={guide.source} target="_blank" rel="noreferrer">{guide.sourceLabel}</a></CardContent>
  </Card>;
}

export default function Help() {
  const [, setLocation] = useLocation();
  const detected = typeof navigator === "undefined" ? "other" : detectInstallBrowser(navigator.userAgent);

  return <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-slate-100 p-4 sm:p-8"><main className="mx-auto max-w-5xl"><Button variant="outline" onClick={() => setLocation("/")} className="mb-6"><ArrowLeft className="mr-2 h-4 w-4" />Voltar</Button><header className="mb-8"><div className="flex items-center gap-2 text-blue-700"><HelpCircle className="h-6 w-6" /><span className="text-sm font-semibold">Centro de ajuda</span></div><h1 className="mt-2 text-3xl font-bold text-slate-900 sm:text-4xl">Instalação e utilização da Liga Toto Talho</h1><p className="mt-3 max-w-3xl text-slate-600">Escolha o guia do seu navegador. A Liga Toto Talho é uma app web: não necessita de descarregar ou instalar ficheiros APK.</p></header><section className="grid gap-5 md:grid-cols-3">{guides.map(guide => <GuideCard key={guide.key} guide={guide} detected={detected} />)}</section><Card className="mt-8 border-emerald-200 bg-emerald-50"><CardContent className="flex gap-3 p-5 text-sm text-emerald-950"><ShieldCheck className="h-5 w-5 shrink-0" /><span><strong>Samsung:</strong> se o Play Protect aparecer, feche o aviso e não escolha “Instalar mesmo assim”. Crie antes o atalho através do menu do Samsung Internet.</span></CardContent></Card><section className="mt-8"><h2 className="text-2xl font-bold text-slate-900">Perguntas frequentes</h2><Accordion type="single" collapsible className="mt-3 rounded-xl border border-slate-200 bg-white px-4"><AccordionItem value="safe"><AccordionTrigger>O aviso do Play Protect significa que o site não é seguro?</AccordionTrigger><AccordionContent>Não. O aviso está ligado ao fluxo de instalação do navegador Samsung. Use o método “Adicionar ao ecrã inicial” descrito acima, sem APK.</AccordionContent></AccordionItem><AccordionItem value="layout"><AccordionTrigger>Surge “Esquema do ecrã inicial bloqueado”. Como resolvo?</AccordionTrigger><AccordionContent>Abra Definições → Ecrã inicial e desative temporariamente Bloquear esquema do ecrã inicial. Depois volte ao Samsung Internet, adicione a Liga Toto Talho ao ecrã inicial e, se quiser, reative o bloqueio depois.</AccordionContent></AccordionItem><AccordionItem value="update"><AccordionTrigger>É preciso atualizar ou reinstalar a app?</AccordionTrigger><AccordionContent>Não. As alterações chegam automaticamente. Se não aparecerem, feche a app e abra novamente.</AccordionContent></AccordionItem><AccordionItem value="login"><AccordionTrigger>Como entro na minha conta?</AccordionTrigger><AccordionContent>Use o email e a password definidos no convite. Se ainda não tiver conta, peça ao administrador um novo convite.</AccordionContent></AccordionItem><AccordionItem value="bets"><AccordionTrigger>Quando consigo ver as apostas dos outros?</AccordionTrigger><AccordionContent>As Apostas Públicas ficam disponíveis após o prazo da jornada fechar.</AccordionContent></AccordionItem></Accordion></section></main></div>;
}
